# Generated by Django 3.1.4 on 2020-12-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_empleado_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=101, verbose_name='nombre_completo'),
        ),
    ]
